/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DebitCard.GUI;

import DebitCard.*;

/**
 * @author Charmaine Helven G. Resma
 * Date: March 3, 2022
 */
public class DebitCardApp extends javax.swing.JFrame {
    DebitCard account;

    /**
     * Creates new form DebitCardApp
     */
    public DebitCardApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTxtAccNumField = new javax.swing.JTextField();
        jTxtAccNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLblAccErrMessage = new javax.swing.JLabel();
        jLblNameErrMessage = new javax.swing.JLabel();
        jTxtBalField = new javax.swing.JTextField();
        jLblBalErrMessage = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBtnCreateAcc = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jBtnDeposit = new javax.swing.JButton();
        jBtnWithdraw = new javax.swing.JButton();
        jBtnCalcInterest = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTxtAmtField = new javax.swing.JTextField();
        jLblAmtErrMessage = new javax.swing.JLabel();
        jTxtRateField = new javax.swing.JTextField();
        jLblRateErrMessage = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLblNewBalance = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLblInterestIncurred = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Input Account Number: ");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Input Account Name: ");

        jLblAccErrMessage.setForeground(new java.awt.Color(255, 51, 0));

        jLblNameErrMessage.setForeground(new java.awt.Color(255, 51, 0));

        jLblBalErrMessage.setForeground(new java.awt.Color(255, 51, 0));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Input Balance: ");

        jBtnCreateAcc.setText("Create Account");
        jBtnCreateAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCreateAccActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTxtAccNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLblAccErrMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtAccNumField, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(jLblNameErrMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jTxtBalField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLblBalErrMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(jBtnCreateAcc)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtAccNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblAccErrMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtAccNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jBtnCreateAcc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblNameErrMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtBalField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblBalErrMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jBtnDeposit.setText("Deposit");
        jBtnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDepositActionPerformed(evt);
            }
        });

        jBtnWithdraw.setText("Withdraw");
        jBtnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWithdrawActionPerformed(evt);
            }
        });

        jBtnCalcInterest.setText("Calc Interest");
        jBtnCalcInterest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCalcInterestActionPerformed(evt);
            }
        });

        jLabel5.setText("Input Amount:");

        jLblAmtErrMessage.setForeground(new java.awt.Color(255, 0, 0));

        jLblRateErrMessage.setForeground(new java.awt.Color(255, 0, 51));

        jLabel8.setText("Input Interest:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLblAmtErrMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxtAmtField, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                            .addComponent(jTxtRateField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLblRateErrMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnCalcInterest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnWithdraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(75, 75, 75))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnDeposit)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTxtAmtField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblAmtErrMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtRateField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblRateErrMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jBtnWithdraw)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jBtnCalcInterest)
                        .addGap(39, 39, 39))))
        );

        jLabel9.setText("New Balance: ");

        jLblNewBalance.setText("0.00");
        jLblNewBalance.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setText("Interest Incurred: ");

        jLblInterestIncurred.setText("0.00%");
        jLblInterestIncurred.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(95, 95, 95)
                        .addComponent(jLblNewBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLblInterestIncurred, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(307, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLblNewBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblInterestIncurred, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * jTxtAccNumField
     * jTxtAccNameField
     * jTxtBalField
     * 
     * jLblAccErrMessage
     * jLblNameErrMessage
     * jLblBalErrMessage
     * 
     * jBtnCreateAcc
     * 
     * jLblNewBalance
     * jLblInterestIncurred
     */
    
    private void jBtnCreateAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCreateAccActionPerformed
        // TODO add your handling code here:
        
        String accountNumber = jTxtAccNumField.getText();
        String[] name = jTxtAccNameField.getText().split(" ");
        
        String firstName = "";
        String middleName = "";
        String lastName = "";
                
        float balance = 0.00F;
        
        
        boolean isValidAccNum = false;
        if(!jTxtAccNumField.getText().equals("")){
            isValidAccNum = true;
            jLblAccErrMessage.setText("");
        } else {
            jLblAccErrMessage.setText("Invalid input");
        }
        
        boolean isValidName = false;
        try {
            firstName = name[0];
            middleName = name[1];
            lastName = name[2];
            isValidName = true;
            jLblNameErrMessage.setText("");
        } catch (Exception e){
            jLblNameErrMessage.setText("Invalid input");
        }
        
        boolean isValidBalance = false;
        try {
            balance = Float.parseFloat(jTxtBalField.getText());
            isValidBalance = true;
            jLblBalErrMessage.setText("");
        } catch (Exception e){
            jLblBalErrMessage.setText("Invalid input");
        }
        
        if(isValidAccNum && isValidName && isValidBalance){
            account = new DebitCard(accountNumber, new Name(firstName, middleName, lastName), balance);
            jTxtAccNumField.setEnabled(false);
            jTxtAccNameField.setEnabled(false);
            jTxtBalField.setEnabled(false);
            jBtnCreateAcc.setEnabled(false);
            jLblNewBalance.setText(String.format("%.2f", account.getBalance()));
        }
    }//GEN-LAST:event_jBtnCreateAccActionPerformed
    
    /**
     * jTxtAmtField
     * jLblAmtErrMessage
     * 
     * jTxtRateField
     * jLblRateErrMessage
     */
    private void jBtnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWithdrawActionPerformed
        // TODO add your handling code here:
        float amtDeposit = 0.00F;
        try {
            amtDeposit = Float.parseFloat(jTxtAmtField.getText());
            //jLblAmtErrMessage.setText("");
            
            if(account.withdrawCash(amtDeposit)){
                jLblNewBalance.setText(String.format("%.2f", account.getBalance()));
                jLblAmtErrMessage.setText("");
            } else {
                jLblAmtErrMessage.setText("Insufficient balance");
            }
        } catch (Exception e){
            jLblAmtErrMessage.setText("Invalid input");
        }
    }//GEN-LAST:event_jBtnWithdrawActionPerformed

    private void jBtnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDepositActionPerformed
        // TODO add your handling code here:
        float amtDeposit = 0.00F;
        
        try {
            amtDeposit = Float.parseFloat(jTxtAmtField.getText());
            jLblNewBalance.setText(String.format("%.2f", account.depositCash(amtDeposit)));
            jLblAmtErrMessage.setText("");
        } catch (Exception e){
            jLblAmtErrMessage.setText("Invalid input");
        }
    }//GEN-LAST:event_jBtnDepositActionPerformed

    private void jBtnCalcInterestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCalcInterestActionPerformed
        // TODO add your handling code here:
        float annualRate = 0.00F;
        try {
            annualRate = Float.parseFloat(jTxtRateField.getText());
            jLblInterestIncurred.setText(String.format("%.2f%%", account.interest(annualRate)));
            jLblNewBalance.setText(String.format("%.2f", account.getBalance()));
            jLblRateErrMessage.setText("");
        } catch(Exception e){
            jLblRateErrMessage.setText("Invalid input");
        }
    }//GEN-LAST:event_jBtnCalcInterestActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCalcInterest;
    private javax.swing.JButton jBtnCreateAcc;
    private javax.swing.JButton jBtnDeposit;
    private javax.swing.JButton jBtnWithdraw;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblAccErrMessage;
    private javax.swing.JLabel jLblAmtErrMessage;
    private javax.swing.JLabel jLblBalErrMessage;
    private javax.swing.JLabel jLblInterestIncurred;
    private javax.swing.JLabel jLblNameErrMessage;
    private javax.swing.JLabel jLblNewBalance;
    private javax.swing.JLabel jLblRateErrMessage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTxtAccNameField;
    private javax.swing.JTextField jTxtAccNumField;
    private javax.swing.JTextField jTxtAmtField;
    private javax.swing.JTextField jTxtBalField;
    private javax.swing.JTextField jTxtRateField;
    // End of variables declaration//GEN-END:variables
}
