/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computer.shop;

import java.sql.*;

/**
 *
 * @author johnfred
 */
public class UserLogin extends javax.swing.JFrame {
    Connection con = null;

    /**
     * Creates new form UserLogin
     */
    public UserLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        LoginMessage = new javax.swing.JOptionPane();
        UserAccountID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UserPasswordField = new javax.swing.JPasswordField();
        AuthenticateLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        PCID = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UserAccountID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserAccountIDActionPerformed(evt);
            }
        });

        jLabel1.setText("Account ID");

        jLabel2.setText("Password");

        UserPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserPasswordFieldActionPerformed(evt);
            }
        });

        AuthenticateLogin.setBackground(new java.awt.Color(0, 153, 204));
        AuthenticateLogin.setForeground(new java.awt.Color(255, 255, 255));
        AuthenticateLogin.setText("Login");
        AuthenticateLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthenticateLoginActionPerformed(evt);
            }
        });

        jLabel3.setText("Current PC");

        PCID.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        PCID.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserAccountID, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(AuthenticateLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                        .addComponent(UserPasswordField))
                    .addComponent(PCID, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PCID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserAccountID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AuthenticateLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserPasswordFieldActionPerformed

    private void AuthenticateLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthenticateLoginActionPerformed
        // TODO add your handling code here:
        
        String sql = "";
        Statement stmt = null;
        ResultSet rs = null;
        
        String uaccountid = "";
        String upassword = "";
        try {
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/computer_shop","root", "");
            
            uaccountid = UserAccountID.getText();
            upassword = UserPasswordField.getText();
            
            // Join the user, account and pc table for to view the record of the user
            
            sql = "SELECT * FROM user LEFT JOIN account ON account.user_id = user.user_id LEFT JOIN pc ON pc.account_id = account.account_id WHERE account.account_id='"+uaccountid+"' AND account.password='"+upassword+"'";
            stmt = con.prepareStatement(sql);
            rs = stmt.executeQuery(sql);
            
            if(rs.next()){
                //Login jframe set visible false to hide login form after login event
                this.setVisible(false);
                //launch the user home with balance preview
                sql = "UPDATE pc SET account_id='"+uaccountid+"' WHERE pc_id='"+PCID.getText()+"'";
                stmt = con.prepareStatement(sql);
                stmt.executeUpdate(sql);
                
                sql = "SELECT * FROM user LEFT JOIN account ON account.user_id = user.user_id LEFT JOIN pc ON pc.account_id = account.account_id WHERE account.account_id='"+uaccountid+"' AND account.password='"+upassword+"'";
                stmt = con.prepareStatement(sql);
                rs = stmt.executeQuery(sql);
                
                if(rs.next()){
                    UserBalance usrbl = new UserBalance(rs.getString("name"), rs.getInt("account_id"),rs.getInt("balance"), rs.getInt("pc_id"));
                    usrbl.show();
                }
            } else {
                LoginMessage.showMessageDialog(this, "Incorrect Password");    
            }
            
        }catch(Exception e){
            LoginMessage.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_AuthenticateLoginActionPerformed

    private void UserAccountIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserAccountIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserAccountIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AuthenticateLogin;
    private javax.swing.JOptionPane LoginMessage;
    private javax.swing.JLabel PCID;
    private javax.swing.JTextField UserAccountID;
    private javax.swing.JPasswordField UserPasswordField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
