/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package computer.shop;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.Timer;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime;    
/**
 *
 * @author johnfred
 */
public class UserBalance extends javax.swing.JFrame {
    /**
     * Creates new form UserBalance
     */
    
    Connection con = null;
    String sql = "";
    Statement stmt = null;
    
    private String uname;
    private int balance;
    private int pc;
    private int account_id;
    public UserBalance(String uname, int account_id, int balance, int pc) {
        initComponents();
        this.uname = uname;
        this.balance = balance;
        this.pc = pc;
        this.account_id = account_id;
        UserName.setText(uname);
        UserPC.setText("PC-"+pc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoutMessage = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        UserName = new javax.swing.JTextField();
        UserBalance = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UserLogout = new javax.swing.JButton();
        UserPC = new javax.swing.JLabel();
        DateTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Name");

        UserName.setEditable(false);
        UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameActionPerformed(evt);
            }
        });

        UserBalance.setEditable(false);

        jLabel2.setText("Balance");

        jLabel3.setText("Date time: ");

        UserLogout.setBackground(new java.awt.Color(0, 153, 204));
        UserLogout.setForeground(new java.awt.Color(255, 255, 255));
        UserLogout.setText("Logout");
        UserLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserLogoutActionPerformed(evt);
            }
        });

        UserPC.setText("PC #");

        DateTime.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserLogout)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(UserBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                .addComponent(UserName))
                            .addComponent(DateTime)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(UserPC)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(UserPC)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DateTime))
                .addGap(38, 38, 38)
                .addComponent(UserLogout)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        T.start();
    }//GEN-LAST:event_formWindowOpened

    private void UserLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserLogoutActionPerformed
        // TODO add your handling code here:
        T.stop();
        try {
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/computer_shop","root", "");
            sql = "UPDATE account SET balance='"+balance+"' WHERE account_id='"+account_id+"'";
            stmt = con.prepareStatement(sql);
            stmt.executeUpdate(sql);
            
            sql = "UPDATE pc SET account_id = NULL WHERE pc_id ='" + this.pc +"'";
            stmt = con.prepareStatement(sql);
            stmt.executeUpdate(sql);

            //UserBalance jframe set visible false to hide login form after login event
            this.setVisible(false);
            //launch the user home with balance preview
            UserLogin usrl = new UserLogin();
            usrl.show();
        }catch(Exception e){
            LogoutMessage.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_UserLogoutActionPerformed

//    int i = this.balance;
    Timer T = new Timer(1000, new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent e) {
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd hh:mm:ss");  
            LocalDateTime now = LocalDateTime.now();  
            
            balance--;
            int secs = balance % 60;
            int hours =  balance / 60;
            int mins = hours % 60;
            hours /= 60;
            if(balance >= 0){
                UserBalance.setText(hours+":"+mins+":"+secs);
            }
            DateTime.setText(dtf.format(now));
        }
    });

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UserBalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UserBalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UserBalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UserBalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UserBalance(uname, balance, pc).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateTime;
    private javax.swing.JOptionPane LogoutMessage;
    private javax.swing.JTextField UserBalance;
    private javax.swing.JButton UserLogout;
    private javax.swing.JTextField UserName;
    private javax.swing.JLabel UserPC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
